import type { ProcessoRow } from "./types";

/** Amostras alinhadas à aba RESUMO do Excel (PILARES II e PSI — contratações). */
export const MOCK_PROCESSOS: ProcessoRow[] = [
  // —— PILARES (trechos reais + consistência para MVP) ——
  {
    bloco: "PILARES",
    processo: "00071.001461/2025-22",
    item: "Locação do Prédio Anexo do INTERPI",
    valor: 1_200_000,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-04-01",
    standByDias: 8,
    alerta: "ATENÇÃO",
    startProcesso: "2025-12-05",
    endProcesso: "2026-04-01",
    diasEmCurso: 117,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Willams",
    alocacaoFocal: null,
    situacao:
      "Na CEL da Seplan, conforme recomendações jurídicas e Regulamento de Aquisições do Banco Mundial.",
  },
  {
    bloco: "PILARES",
    processo: "00071.004341/2025-87",
    item: "Vigilância e monitoramento eletrônico 24h",
    valor: 67_953,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-08-15",
    endProcesso: null,
    diasEmCurso: 237,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Suely",
    alocacaoFocal: null,
    situacao: "Encaminhado à SEPLAN — fase externa da contratação.",
  },
  {
    bloco: "PILARES",
    processo: "00071.004461/2025-84",
    item: "Equipamentos de informática e eletrônicos (INTERPI e GAECO/MPPI)",
    valor: 1_528_887.86,
    onde: "DSIG",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-08-26",
    endProcesso: null,
    diasEmCurso: 226,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Daniela",
    alocacaoFocal: null,
    situacao: "Aguardando resposta da pesquisa de mercado junto aos fornecedores.",
  },
  {
    bloco: "PILARES",
    processo: "00071.000601/2026-26",
    item: "Mobiliário e aparelhos de ar condicionado",
    valor: 699_562.2,
    onde: "DAFIN",
    ultimaMovimentacao: "2026-04-01",
    standByDias: 8,
    alerta: "ATENÇÃO",
    startProcesso: "2026-03-10",
    endProcesso: null,
    diasEmCurso: 30,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Daniela",
    alocacaoFocal: null,
    situacao: "Revisão do descritivo.",
  },
  {
    bloco: "PILARES",
    processo: "00071.003837/2025-33",
    item: "Aquisição de licença Topocad",
    valor: 150_000,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-07-23",
    endProcesso: null,
    diasEmCurso: 260,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Willams",
    alocacaoFocal: null,
    situacao:
      "CPL enviou justificativa de preço à SEPLAN; aguardando resposta do Banco sobre mudança de metodologia.",
  },
  {
    bloco: "PILARES",
    processo: "00071.004465/2025-62",
    item: "Aquisição de marcos demarcatórios para o INTERPI",
    valor: 825_000,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-08-26",
    endProcesso: null,
    diasEmCurso: 226,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Suely",
    alocacaoFocal: null,
    situacao: "Aguardando devolução do processo pela SEPLAN (licitação por lote com equipamentos de GEO).",
  },
  {
    bloco: "PILARES",
    processo: "00071.004462/2025-29",
    item: "Equipamentos de georreferenciamento INTERPI e GAECO/MPPI",
    valor: 3_112_513.43,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-03-24",
    standByDias: 16,
    alerta: "CRÍTICO",
    startProcesso: "2025-08-26",
    endProcesso: null,
    diasEmCurso: 226,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Willams",
    alocacaoFocal: null,
    situacao: "Aguardando parecer da PGE.",
  },
  {
    bloco: "PILARES",
    processo: "00017.002609/2025-09",
    item: "Aquisição de EPI para GAECO/MPPI",
    valor: 1_860,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-04-01",
    standByDias: 8,
    alerta: "ATENÇÃO",
    startProcesso: "2025-08-29",
    endProcesso: "2026-04-01",
    diasEmCurso: 215,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: null,
    alocacaoFocal: "Externo",
    situacao: "Em licitação pela SEPLAN; processo unificado (INTERPI, SAF e SEMAR).",
  },
  {
    bloco: "PILARES",
    processo: "00017.002624/2025-49",
    item: "Aquisição de 17 veículos (INTERPI / GERCOG / FORO)",
    valor: 5_249_356,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-08-13",
    endProcesso: null,
    diasEmCurso: 239,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Whashigton",
    alocacaoFocal: null,
    situacao: "CPL encaminhou autos com adequações da CGE; comissão nomeada pela Seplan.",
  },
  {
    bloco: "PILARES",
    processo: "00071.004236/2025-48",
    item: "Locação de veículos (INTERPI) — 09 veículos",
    valor: 8_336_250,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-08-12",
    endProcesso: null,
    diasEmCurso: 240,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Breno",
    alocacaoFocal: null,
    situacao: "Processo encaminhado à SEPLAN com o TDR.",
  },
  {
    bloco: "PILARES",
    processo: "00071.003835/2025-44",
    item: "Contratação de empresa (combustível e manutenção de frota)",
    valor: 4_565_135.5,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-07-23",
    endProcesso: null,
    diasEmCurso: 260,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Suely",
    alocacaoFocal: null,
    situacao: "Processo na SEPLAN.",
  },
  {
    bloco: "PILARES",
    processo: "00071.005990/2025-03",
    item: "Locação de internet via Starlink",
    valor: 2_383_953.52,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-03-31",
    standByDias: 9,
    alerta: "ATENÇÃO",
    startProcesso: "2025-11-06",
    endProcesso: null,
    diasEmCurso: 154,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Suely",
    alocacaoFocal: null,
    situacao: "Encaminhado à SEPLAN — fase externa.",
  },
  {
    bloco: "PILARES",
    processo: "00071.006134/2025-67",
    item: "Adaptação da sede do INTERPI",
    valor: 1_800_000,
    onde: "SEAD",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-11-19",
    endProcesso: null,
    diasEmCurso: 141,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Rodrigo",
    alocacaoFocal: null,
    situacao: "DAFIN → SEAD: possível cessão de servidor com formação em arquitetura para projeto.",
  },
  {
    bloco: "PILARES",
    processo: "00071.005987/2025-81",
    item: "Fortalecimento da comunicação do INTERPI",
    valor: 2_000_000,
    onde: "ASPLAN",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-11-06",
    endProcesso: null,
    diasEmCurso: 154,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Rodrigo",
    alocacaoFocal: null,
    situacao: "Alinhamento de especificações técnicas com a SECOM.",
  },
  {
    bloco: "PILARES",
    processo: "00071.005988/2025-26",
    item: "Placas sinalizadoras para territórios (PCT)",
    valor: 57_000,
    onde: "DPCT",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-11-06",
    endProcesso: null,
    diasEmCurso: 154,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Saullo",
    alocacaoFocal: null,
    situacao: "DPCT a informar comunidades e distâncias para entrega das placas.",
  },
  {
    bloco: "PILARES",
    processo: "Pendente criação",
    item: "Contratação de empresa (sistema)",
    valor: 2_500_000,
    onde: "ASPLAN",
    ultimaMovimentacao: "2026-03-26",
    standByDias: 14,
    alerta: "CRÍTICO",
    startProcesso: null,
    endProcesso: null,
    diasEmCurso: null,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Vinicius",
    alocacaoFocal: null,
    situacao: "Objeto alterado; TDR em elaboração; contratação direta.",
  },
  {
    bloco: "PILARES",
    processo: "Pendente criação",
    item: "Contratação de empresa — diagnóstico rápido",
    valor: 3_000_000,
    onde: "ASPLAN",
    ultimaMovimentacao: "2026-03-26",
    standByDias: 14,
    alerta: "CRÍTICO",
    startProcesso: null,
    endProcesso: null,
    diasEmCurso: null,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Simone",
    alocacaoFocal: null,
    situacao: "ASPLAN elaborando e validando o TDR.",
  },
  {
    bloco: "PILARES",
    processo: "Pendente criação",
    item: "Contratação de empresa — eventos regionais",
    valor: 1_082_784,
    onde: "ASPLAN",
    ultimaMovimentacao: "2026-03-12",
    standByDias: 28,
    alerta: "CRÍTICO",
    startProcesso: null,
    endProcesso: null,
    diasEmCurso: null,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Simone",
    alocacaoFocal: null,
    situacao: "Verificar evento conjunto DPCT (Saullo, Rodrigo e Vinicius).",
  },
  {
    bloco: "PILARES",
    processo: "00071.006201/2025-14",
    item: "Infraestrutura e soluções corporativas de TI (lote consolidado)",
    valor: 4_329_489.66,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-04-01",
    standByDias: 8,
    alerta: "ATENÇÃO",
    startProcesso: "2025-10-01",
    endProcesso: null,
    diasEmCurso: 182,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Willams",
    alocacaoFocal: null,
    situacao: "Processo na SEPLAN — fase de licitação.",
  },
  {
    bloco: "PILARES",
    processo: "00071.006215/2026-03",
    item: "Aquisição de materiais de expediente e consumo",
    valor: 33_184,
    onde: "DAFIN",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "OK",
    startProcesso: "2026-02-15",
    endProcesso: null,
    diasEmCurso: 44,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Daniela",
    alocacaoFocal: null,
    situacao: "Cotação em análise na DAFIN.",
  },
  {
    bloco: "PILARES",
    processo: "00071.005842/2025-91",
    item: "Obras e reformas em unidades descentralizadas",
    valor: 25_047_692.31,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-06-20",
    endProcesso: null,
    diasEmCurso: 285,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Breno",
    alocacaoFocal: null,
    situacao: "Projeto básico em revisão junto à SEPLAN.",
  },
  {
    bloco: "PILARES",
    processo: "00071.004998/2025-77",
    item: "Contratação integrada de serviços de engenharia e fiscalização",
    valor: 33_396_923.08,
    onde: "SEPLAN",
    ultimaMovimentacao: "2026-03-28",
    standByDias: 12,
    alerta: "CRÍTICO",
    startProcesso: "2025-05-10",
    endProcesso: null,
    diasEmCurso: 325,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Suely",
    alocacaoFocal: null,
    situacao: "Pendência de documentação complementar para publicação.",
  },
  {
    bloco: "PILARES",
    processo: "00017.003102/2025-61",
    item: "Aquisição de equipamentos e sistemas para GAECO/MPPI (lote único)",
    valor: 14_576_365.38,
    onde: "GAECO",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-09-05",
    endProcesso: null,
    diasEmCurso: 207,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: null,
    alocacaoFocal: "Externo",
    situacao: "Tramitação conjunta INTERPI / MP — aguardando parecer técnico.",
  },
  {
    bloco: "PILARES",
    processo: "00071.006089/2025-55",
    item: "Serviços de consultoria especializada em planejamento estratégico",
    valor: 2_000_000,
    onde: "DG",
    ultimaMovimentacao: "2026-04-01",
    standByDias: 8,
    alerta: "ATENÇÃO",
    startProcesso: "2025-11-25",
    endProcesso: null,
    diasEmCurso: 128,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Rodrigo",
    alocacaoFocal: null,
    situacao: "Seleção de consultoria em curso na DG.",
  },
  // —— PSI (valores e itens alinhados à planilha PSI) ——
  {
    bloco: "PSI",
    processo: "PSI-2025-GEOREF",
    item: "Equipamentos de georreferenciamento",
    valor: 1_073_400,
    onde: "DAFIN",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-08-01",
    endProcesso: null,
    diasEmCurso: 242,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Willams",
    alocacaoFocal: null,
    situacao: "Tramitação na DAFIN.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-INFO",
    item: "Equipamentos de informática",
    valor: 449_011,
    onde: "",
    ultimaMovimentacao: "2026-04-01",
    standByDias: 8,
    alerta: "ATENÇÃO",
    startProcesso: "2025-09-15",
    endProcesso: null,
    diasEmCurso: 198,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Daniela",
    alocacaoFocal: null,
    situacao: "Especificações técnicas em revisão.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-MAP",
    item: "Empresa para o mapeamento de processos",
    valor: 1_202_940,
    onde: "",
    ultimaMovimentacao: "2026-03-28",
    standByDias: 12,
    alerta: "CRÍTICO",
    startProcesso: "2025-07-01",
    endProcesso: null,
    diasEmCurso: 275,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Simone",
    alocacaoFocal: null,
    situacao: "Seleção de fornecedor em andamento.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-VEIC",
    item: "Locação de veículos",
    valor: 5_436_468,
    onde: "",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-06-10",
    endProcesso: null,
    diasEmCurso: 295,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Breno",
    alocacaoFocal: null,
    situacao: "Processo na SEPLAN.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-CAP",
    item: "Capacitação e treinamentos",
    valor: 495_000,
    onde: "",
    ultimaMovimentacao: "2026-04-01",
    standByDias: 8,
    alerta: "OK",
    startProcesso: "2025-11-01",
    endProcesso: null,
    diasEmCurso: 151,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Carla",
    alocacaoFocal: null,
    situacao: "Cronograma de turmas em definição.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-AGR4",
    item: "Consultoria agrimensura (4)",
    valor: 2_678_400,
    onde: "",
    ultimaMovimentacao: "2026-03-25",
    standByDias: 15,
    alerta: "CRÍTICO",
    startProcesso: "2025-05-20",
    endProcesso: null,
    diasEmCurso: 316,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Suely",
    alocacaoFocal: null,
    situacao: "Fase de habilitação.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-AGRO-A",
    item: "Consultoria agronomia (1)",
    valor: 669_660,
    onde: "",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-10-01",
    endProcesso: null,
    diasEmCurso: 182,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Rodrigo",
    alocacaoFocal: null,
    situacao: "Parecer técnico pendente.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-SS3",
    item: "Consultoria serviço social (3)",
    valor: 2_008_800,
    onde: "",
    ultimaMovimentacao: "2026-03-29",
    standByDias: 11,
    alerta: "ATENÇÃO",
    startProcesso: "2025-06-01",
    endProcesso: null,
    diasEmCurso: 303,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Breno",
    alocacaoFocal: null,
    situacao: "Edital em elaboração.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-SI2",
    item: "Consultoria sistema de informação (2)",
    valor: 1_339_200,
    onde: "",
    ultimaMovimentacao: "2026-04-02",
    standByDias: 7,
    alerta: "CRÍTICO",
    startProcesso: "2025-08-20",
    endProcesso: null,
    diasEmCurso: 225,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Daniela",
    alocacaoFocal: null,
    situacao: "Adequação de requisitos de TI.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-SOC1",
    item: "Consultoria sociologia (1)",
    valor: 669_660,
    onde: "",
    ultimaMovimentacao: "2026-03-27",
    standByDias: 13,
    alerta: "ATENÇÃO",
    startProcesso: "2025-11-10",
    endProcesso: null,
    diasEmCurso: 142,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Simone",
    alocacaoFocal: null,
    situacao: "Proposta em análise.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-ANT-A",
    item: "Consultoria antropologia (1)",
    valor: 669_660,
    onde: "",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2025-09-05",
    endProcesso: null,
    diasEmCurso: 207,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Simone",
    alocacaoFocal: null,
    situacao: "Cotações recebidas.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-AGRO-B",
    item: "Consultoria agronomia (1)",
    valor: 401_760,
    onde: "",
    ultimaMovimentacao: "2026-04-01",
    standByDias: 8,
    alerta: "OK",
    startProcesso: "2026-01-10",
    endProcesso: null,
    diasEmCurso: 81,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Carla",
    alocacaoFocal: null,
    situacao: "Em conformidade com etapa atual.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-ADM1",
    item: "Consultoria administração (1)",
    valor: 401_760,
    onde: "",
    ultimaMovimentacao: "2026-04-01",
    standByDias: 8,
    alerta: "OK",
    startProcesso: "2026-01-12",
    endProcesso: null,
    diasEmCurso: 79,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Carla",
    alocacaoFocal: null,
    situacao: "Documentação em análise na DAFIN.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-CINT-A",
    item: "CINTERPI (contratação de empresa)",
    valor: 110_220,
    onde: "",
    ultimaMovimentacao: "2026-03-31",
    standByDias: 9,
    alerta: "ATENÇÃO",
    startProcesso: "2025-12-01",
    endProcesso: null,
    diasEmCurso: 120,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Vinicius",
    alocacaoFocal: null,
    situacao: "Tramitação inicial.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-CINT-B",
    item: "CINTERPI (convite palestra)",
    valor: null,
    onde: "",
    ultimaMovimentacao: "2026-03-15",
    standByDias: 25,
    alerta: "ATENÇÃO",
    startProcesso: null,
    endProcesso: null,
    diasEmCurso: null,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Carla",
    alocacaoFocal: null,
    situacao: "Convite em elaboração — sem VALOR na planilha.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-AUDIO",
    item: "Aquisição de caixas de som, microfones e equipamentos de áudio",
    valor: 10_364.4,
    onde: "",
    ultimaMovimentacao: "2026-04-02",
    standByDias: 7,
    alerta: "OK",
    startProcesso: "2026-02-01",
    endProcesso: null,
    diasEmCurso: 60,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Daniela",
    alocacaoFocal: null,
    situacao: "Aquisição de equipamentos de áudio — cotação em análise.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-WS",
    item: "Aquisição de computadores (workstation) e tablets",
    valor: 152_000,
    onde: "",
    ultimaMovimentacao: "2026-04-01",
    standByDias: 8,
    alerta: "ATENÇÃO",
    startProcesso: "2025-11-20",
    endProcesso: null,
    diasEmCurso: 132,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Daniela",
    alocacaoFocal: null,
    situacao: "Pesquisa de preços em curso.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-ANT-B",
    item: "Consultoria antropologia (1)",
    valor: 401_760,
    onde: "",
    ultimaMovimentacao: "2026-03-30",
    standByDias: 10,
    alerta: "ATENÇÃO",
    startProcesso: "2026-01-05",
    endProcesso: null,
    diasEmCurso: 86,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Simone",
    alocacaoFocal: null,
    situacao: "Segunda contratação no mesmo objeto.",
  },
  {
    bloco: "PSI",
    processo: "PSI-2025-AGRM-C",
    item: "Consultoria agrimensor (1)",
    valor: 401_760,
    onde: "",
    ultimaMovimentacao: "2026-03-29",
    standByDias: 11,
    alerta: "CRÍTICO",
    startProcesso: "2025-07-15",
    endProcesso: null,
    diasEmCurso: 260,
    termoEnc: "Ausente",
    dfd: "Incluso",
    trd: "Ausente",
    responsavel: "Suely",
    alocacaoFocal: null,
    situacao: "Prazo de resposta externa.",
  },
];
